## post company 3M
POST http://localhost:8080/company
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJncmFjZSIsInJvbGVzIjpbIlJPTEVfUkVBRCJdLCJpYXQiOjE3MDIwMjcyODAsImV4cCI6MTcwMjAzMDg4MH0.sakUpWuvFzlEEZ17NifqJaRS_BenORg-7H8c7SYn4z0iJbnXsW3ELxlswHfKzqS0zdbh_49U1nlbWq_n0DbQaA

Content-Type: application/json

{
  "ticker": "MMM"
}

### post company
POST http://localhost:8080/company
Content-Type: application/json

{
  "ticker": "AAPL"
}

### post company-Invesco QQQ Trust
POST http://localhost:8080/company
Content-Type: application/json

{
  "ticker": "QQQ"
}

### post company-Nike
POST http://localhost:8080/company
Content-Type: application/json

{
  "ticker": "NKE"
}

### post company-Spor S&P 500 ETF Trust
POST http://localhost:8080/company
Content-Type: application/json

{
  "ticker": "SPY"
}

### 전체 회사 조회
GET http://localhost:8080/company?size=5&page=1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJncmFjZSIsInJvbGVzIjpbIlJPTEVfUkVBRCJdLCJpYXQiOjE3MDIwMjcyODAsImV4cCI6MTcwMjAzMDg4MH0.sakUpWuvFzlEEZ17NifqJaRS_BenORg-7H8c7SYn4z0iJbnXsW3ELxlswHfKzqS0zdbh_49U1nlbWq_n0DbQaA

