### post company
POST http://localhost:8080/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJncmFjZSIsInJvbGVzIjpbIlJPTEVfUkVBRCIsIlJPTEVfV1JJVEUiXSwiaWF0IjoxNzAyMDQ0Mzg5LCJleHAiOjE3MDIwNDc5ODl9.yzCGG6TOoIyskxH72CdH-NC-O9_gwfb5WZbxgCc5_rQdC9Tn1cZmbroY66I3al_YQUXydaZsn8hvbgzIkzUhhQ

{
  "ticker": "MMM"
}

### post company
POST http://localhost:8080/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJncmFjZSIsInJvbGVzIjpbIlJPTEVfUkVBRCIsIlJPTEVfV1JJVEUiXSwiaWF0IjoxNzAyMDQ0Mzg5LCJleHAiOjE3MDIwNDc5ODl9.yzCGG6TOoIyskxH72CdH-NC-O9_gwfb5WZbxgCc5_rQdC9Tn1cZmbroY66I3al_YQUXydaZsn8hvbgzIkzUhhQ

{
  "ticker": "AAPL"
}

### post company-Invesco QQQ Trust
POST http://localhost:8080/company
Content-Type: application/json

{
  "ticker": "QQQ"
}

### post company-Nike
POST http://localhost:8080/company
Content-Type: application/json

{
  "ticker": "NKE"
}

### post company-Spor S&P 500 ETF Trust
POST http://localhost:8080/company
Content-Type: application/json

{
  "ticker": "SPY"
}

### 전체 회사 조회
GET http://localhost:8080/company?size=5&page=1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJncmFjZSIsInJvbGVzIjpbIlJPTEVfUkVBRCIsIlJPTEVfV1JJVEUiXSwiaWF0IjoxNzAyMDQ0Mzg5LCJleHAiOjE3MDIwNDc5ODl9.yzCGG6TOoIyskxH72CdH-NC-O9_gwfb5WZbxgCc5_rQdC9Tn1cZmbroY66I3al_YQUXydaZsn8hvbgzIkzUhhQ

